baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Awesome Hugo Site'

description = "Woohoo that's a nice blender"

[params.github]
repository="indrora/leap-day-hugo"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
