baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Awesome Hugo Site'

[params]
description = "Isn't the weather nice?"

[params.github]
repository="indrora/leap-day-hugo"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[markup]
  [markup.highlight]
    style = 'catppuccin-mocha'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
